-- 멀티 판매처 시드: 같은 품목을 여러 판매처가 다른 D-day·가격으로 판매(가격 비교용).
-- 배포 재현용: docker-entrypoint-initdb.d 05-multiseller.sql 로 실행됨.
DELETE FROM products WHERE description LIKE '[멀티판매처]%';
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (1001,'무농약 청상추','[멀티판매처] 초록들녘농장 산지직송','vegetable',3500,12,'/seed-images/p1.jpg',DATE_ADD(CURDATE(),INTERVAL 2 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (1002,'무농약 청상추','[멀티판매처] 동해바다수산 산지직송','vegetable',4200,8,'/seed-images/p1.jpg',DATE_ADD(CURDATE(),INTERVAL 10 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (1003,'친환경 방울토마토','[멀티판매처] 햇살가득과수원 산지직송','vegetable',5000,18,'/seed-images/p2.jpg',DATE_ADD(CURDATE(),INTERVAL 5 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (11,'친환경 방울토마토','[멀티판매처] (주)가야농산 산지직송','vegetable',5900,13,'/seed-images/p2.jpg',DATE_ADD(CURDATE(),INTERVAL 8 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (26,'완숙 토마토','[멀티판매처] (유)신라농산 산지직송','vegetable',5800,24,'/seed-images/p3.jpg',DATE_ADD(CURDATE(),INTERVAL 9 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (27,'완숙 토마토','[멀티판매처] (주)조선인포센터농산 산지직송','vegetable',7000,18,'/seed-images/p3.jpg',DATE_ADD(CURDATE(),INTERVAL 3 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (12,'제주 노지 감귤 2kg','[멀티판매처] (주)가야고려상사농산 산지직송','fruit',11600,30,'/seed-images/p4.jpg',DATE_ADD(CURDATE(),INTERVAL 12 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (1001,'제주 노지 감귤 2kg','[멀티판매처] 초록들녘농장 산지직송','fruit',13900,23,'/seed-images/p4.jpg',DATE_ADD(CURDATE(),INTERVAL 6 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (1002,'국산 손질 오징어','[멀티판매처] 동해바다수산 산지직송','seafood',8000,36,'/seed-images/p5.jpg',DATE_ADD(CURDATE(),INTERVAL 3 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (1003,'국산 손질 오징어','[멀티판매처] 햇살가득과수원 산지직송','seafood',9600,8,'/seed-images/p5.jpg',DATE_ADD(CURDATE(),INTERVAL 13 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (11,'한우 불고기용 300g','[멀티판매처] (주)가야농산 산지직송','meat',17000,12,'/seed-images/p6.jpg',DATE_ADD(CURDATE(),INTERVAL 8 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (26,'한우 불고기용 300g','[멀티판매처] (유)신라농산 산지직송','meat',20400,13,'/seed-images/p6.jpg',DATE_ADD(CURDATE(),INTERVAL 4 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (27,'유기농 시금치','[멀티판매처] (주)조선인포센터농산 산지직송','vegetable',3800,18,'/seed-images/p7.jpg',DATE_ADD(CURDATE(),INTERVAL 11 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (12,'유기농 시금치','[멀티판매처] (주)가야고려상사농산 산지직송','vegetable',4500,18,'/seed-images/p7.jpg',DATE_ADD(CURDATE(),INTERVAL 9 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (1,'유기농 양파 1.5kg','[멀티판매처] 도연농장 산지직송','vegetable',4300,24,'/seed-images/p8.jpg',DATE_ADD(CURDATE(),INTERVAL 4 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (1002,'유기농 양파 1.5kg','[멀티판매처] 동해바다수산 산지직송','vegetable',5200,23,'/seed-images/p8.jpg',DATE_ADD(CURDATE(),INTERVAL 12 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (1003,'친환경 깻잎 100g','[멀티판매처] 햇살가득과수원 산지직송','vegetable',2000,30,'/seed-images/p9.jpg',DATE_ADD(CURDATE(),INTERVAL 7 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (11,'친환경 깻잎 100g','[멀티판매처] (주)가야농산 산지직송','vegetable',2400,8,'/seed-images/p9.jpg',DATE_ADD(CURDATE(),INTERVAL 2 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (26,'손질 고등어 2손','[멀티판매처] (유)신라농산 산지직송','seafood',10700,36,'/seed-images/p10.jpg',DATE_ADD(CURDATE(),INTERVAL 13 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (27,'손질 고등어 2손','[멀티판매처] (주)조선인포센터농산 산지직송','seafood',12900,13,'/seed-images/p10.jpg',DATE_ADD(CURDATE(),INTERVAL 7 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (12,'생물 오징어 3마리','[멀티판매처] (주)가야고려상사농산 산지직송','seafood',8800,12,'/seed-images/p11.jpg',DATE_ADD(CURDATE(),INTERVAL 6 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (1,'생물 오징어 3마리','[멀티판매처] 도연농장 산지직송','seafood',10600,18,'/seed-images/p11.jpg',DATE_ADD(CURDATE(),INTERVAL 11 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (1001,'햇사과 5입','[멀티판매처] 초록들녘농장 산지직송','fruit',12200,18,'/seed-images/p12.jpg',DATE_ADD(CURDATE(),INTERVAL 10 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (1002,'햇사과 5입','[멀티판매처] 동해바다수산 산지직송','fruit',14600,23,'/seed-images/p12.jpg',DATE_ADD(CURDATE(),INTERVAL 5 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (11,'꿀배 4입','[멀티판매처] (주)가야농산 산지직송','fruit',14400,24,'/seed-images/p13.jpg',DATE_ADD(CURDATE(),INTERVAL 2 DAY));
INSERT INTO products (seller_id,name,description,category,price,stock_qty,thumbnail_url,expiration_date) VALUES (26,'꿀배 4입','[멀티판매처] (유)신라농산 산지직송','fruit',17300,8,'/seed-images/p13.jpg',DATE_ADD(CURDATE(),INTERVAL 8 DAY));
